### ISSUE TITLE
Minor details in the documentation

### ISSUE THREAD

**Issue by jrvalverde** [liresearchgroup/chronusq_public#2]
First of all, thanks a lot for opening up the package. It certainly looks most promising.

Then, as I started trying ChronusQ, I found that the coordinates in the geom section **must** contain at least one space before the atom name. Without it, the program does not recognize them. This is not mentioned in the documentation and puzzled me a lot. It is likely better to fix the parser.

In researching this, I looked at the example files and found what was initially surprising, a zero after all atom names and before the coordinates. A look at parseMolecule.py shows that this is an optional thing, and that this number is intended to identify at some point in the future the isotope to use. This is not an issue at all, and I am absolutely OK with it, and understand it not being mentioned in the documentation until it is definitively available, but it is puzzling nonetheless. I would suggest that at least a README in Test/UNIT mention this to avoid puzzling new users who look there for sample input files.

**Comment by wavefunction91** [comment]
These have been addressed in:
b6750b0305
a802e1aeda
b86d20ea150
